name: Release

on:
  # Run the workflow each time new commits are pushed to the candidate branch. 
  push:
    branches: [ "candidate" ]
  workflow_dispatch:
    inputs:
      enable_ssh_access:
        type: boolean
        description: 'Enable ssh access'
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  get-architectures:
    name: 🖥 Get snap architectures
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.get-architectures.outputs.architectures }}
      architectures-list: ${{ steps.get-architectures.outputs.architectures-list }}
    steps:
      - name: 🖥 Get snap architectures
        id: get-architectures
        uses: snapcrafters/ci/get-architectures@main

  release:
    name: 🚢 Release to latest/candidate
    needs: get-architectures
    runs-on: ubuntu-latest
    environment: "Candidate Branch"
    strategy:
      matrix:
        architecture: ${{ fromJSON(needs.get-architectures.outputs.architectures-list) }}
    steps:
      - name: Enable ssh access
        uses: mxschmitt/action-tmate@v3
        if: ${{ inputs.enable_ssh_access }}
        with:
          limit-access-to-actor: true
      - name: remote build
        run: |
          mkdir -p ~/.local/share/snapcraft
          echo -e "${{ secrets.LP_BUILD_SECRET }}" > ~/.local/share/snapcraft/launchpad-credentials
          sudo snap install snapcraft --classic
          snapcraft init
          git init
          snapcraft init
          CRAFT_DEBUG=1 snapcraft remote-build --launchpad-accept-public-upload --verbosity=trace --build-for arm64
